# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfS2EM3DrCPDPuwAwDxyizhmWTFizPYw
"""

name = input("Enter your name: ")
print("Hello, ", name)